### ISSUE TITLE
Can we get a regular EXE to install the agent?

### ISSUE THREAD

**Issue by softwareguy74** [awslabs/kinesis-agent-windows#1]
Why must we go through PowerShell?  I'd like to be able to download an EXE and go from there.

**Comment by bfeinb** [comment]
That's an excellent suggestion.  Would you prefer it if the EXE was self-contained, or would it be OK if the EXE downloaded items from S3?

Folks, please vote on this item if it is important to you so we can prioritize this work correctly.  Thanks for the feedback!

**Comment by aspcompiler** [comment]
@softwareguy74,  many users automate the deployment to a number of systems using EC2 User Data, Run Command so a single command Powershell deployment is convenient. If there are demands for Exe installation, we will definitely support it. 

Are you looking to download exe and install on each system or use a management platform?

**Comment by bfeinb** [comment]
Also, does it need to be an .EXE or would an .MSI be OK?

**Comment by softwareguy74** [comment]
MSI would be fine.  This is for the cases where we are providing a custom solution to a client in which they download our app from our site and do the install on their side.  This is a different use case than the mass installation via PowerShell that someone else mentioned here.  I think having both options is nice.

**Comment by bfeinb** [comment]
OK, thanks for this suggestion.  We'll post back on this thread once we have an MSI or EXE installer for your use.

**Comment by softwareguy74** [comment]
Any update on providing a regular installer for this?

**Comment by aspcompiler** [comment]
We are on it. Will get back to you soon.

**Comment by aspcompiler** [comment]
@softwareguy74 , We have an msi installer beta at https://s3-us-west-2.amazonaws.com/kinesis-agent-windows/beta/index.html. Could you give it a try and let us know if it works for you?

**Comment by aspcompiler** [comment]
1.1 released to production with an msi installer.
