### ISSUE TITLE
Windows Sysmon Source Declarations

### ISSUE THREAD

**Issue by secdev-01** [awslabs/kinesis-agent-windows#10]
Is there currently a Windows Sysmon Source Declaration? Are there any plans to develop one?

The Sysmon collector allows for several endpoint related events to be streamed.

https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon

Thank you in advance.

**Comment by dhhoang** [comment]
Hi @secdev-01 ,
It looks like Sysmon generates events to Windows Event logs. Have you tried collecting the events from the "Applications and Services Logs/Microsoft/Windows/Sysmon/Operational" log?

**Comment by secdev-01** [comment]
I'll give that a try , thanks.
