### ISSUE TITLE
When build is executed nuget.exe is not found 

### ISSUE THREAD

**Issue by Mahalakshmi-Shanmugam** [awslabs/kinesis-agent-windows#16]
I am in Powershell and trying to execute Build.ps1. The error is that nuget.exe can not be found as part of a CmdLet, Function or script. But nuget.exe is in the directory from which I execute build.ps1

**Comment by dhhoang** [comment]
See our doc: https://github.com/awslabs/kinesis-agent-windows#building-from-the-source-code

> To build the nuget package, make sure you have nuget.exe in the path, open an elevated PowerShell command prompt, navigate to the project root directory, and run “.\build.ps1”.

So you need to have `nuget.exe` in the path. I'd recommend put that in the same folder that you have with `MsBuild.exe`. Something like:
```
Get-Command  MSBuild.exe | select -ExpandProperty Source
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe
```

**Comment by Mahalakshmi-Shanmugam** [comment]
@dhhoang Thanks. It worked. I had the nuget.exe in my project folder when I had the issue. After adding it to the MSBuild folder it worked. Thank you.
