### ISSUE TITLE
Any plans to switch to .NET Core?

### ISSUE THREAD

**Issue by TFTomSun** [awslabs/kinesis-agent-windows#3]
Are there any plans to switch to .NET Core, so that we can have one self contained agent that runs on all operating systems and platforms? I don't understand why there are 2 implementations of the agent and i am afraid that they will behave different.

Best regards,
Thomas

**Comment by aspcompiler** [comment]
Thanks for reaching out to us, Thomas.

Switching to .net core is on our roadmap and is feasible. I have a couple of questions for you:
1) Are you looking for Windows only or are you also looking for some Linux distributions and Mac? If Linux, please let us know the distribution and the version.
2) Our existing package is about 6MB. A self-contained distribution would be around 28MB. Would the size increase be any issue for you?

As for 2 implementations, do you refer https://github.com/awslabs/amazon-kinesis-agent and https://github.com/awslabs/kinesis-agent-windows? They were just two different products with different origins to address different customer needs. Amazon Kinesis Agent for Windows started as an internal agent by Windows teams to meet the Windows monitoring need before made available to the public.

**Comment by softwareguy74** [comment]
This is a must.   Need to be able to run on both Windows and Linux.  For myself, I'm looking for Amazon Linux support.  I realize there is a difference in operating system events but looking to be able to monitor a specific directory for application log files to stream to Kinesis.

**Comment by aspcompiler** [comment]
Hi softwareguy74@, since the discussion could possibly involve our unreleased products, could you reach out to amazonli@amazon.com?

**Comment by skumawat1984** [comment]
Hi softwareguy74, TFTomSun 

Beta build is now available with .NET Core 5.0. Pls check the details at https://github.com/awslabs/kinesis-agent-windows/releases

**Comment by dhhoang** [comment]
We have moved to .NET 6. Closing this.
