### ISSUE TITLE
Can't Install the Agent

### ISSUE THREAD

**Issue by gauchoux** [awslabs/kinesis-agent-windows#4]
Hi,

I just can't install the agent I have tried every method and I keep getting errors.
I've tried digging into them but I can't find anything...
![image](https://user-images.githubusercontent.com/23196279/52715155-ffd38780-2f9b-11e9-9c9a-95930c4a3b5e.png)
![image](https://user-images.githubusercontent.com/23196279/52715168-0a8e1c80-2f9c-11e9-8a44-c03633639446.png)
![image](https://user-images.githubusercontent.com/23196279/52715210-1e398300-2f9c-11e9-91f0-03893991382e.png)

Could you help me out ?
Thanks !

**Comment by aspcompiler** [comment]
Hi @gauchoux , it appears that you downloaded InstallKinesisAgent.ps1 first and ran it, right? 

In Windows Explorer, right-click InstallKinesisAgent.ps1, select properties. If it is blocked, unblock it and run InstallKinesisAgent.ps1 again. Let me know if this is the issue.

**Comment by gauchoux** [comment]
Hi @aspcompiler ,

First, thanks for your fast response, much appreciated ! 
So it was indeed blocked but unblocking it hasn't solved the problem...
Output:
![image](https://user-images.githubusercontent.com/23196279/52788110-3b378a00-3060-11e9-95c8-5b6dbe9893ca.png)

**Comment by gauchoux** [comment]
It seems to be the same error as before it was unblocked.

**Comment by aspcompiler** [comment]
@gauchoux , do you know if your environment uses a proxy server to access the internet? You can usually find out from your browser proxy configuration. Which browser did you use to download InstallKinesisAgent.ps1? 

If InstallKinesisAgent.ps1 is not able to download files from the internet, an alternative is to follow the "Download Manually" section on the download page: https://s3-us-west-2.amazonaws.com/kinesis-agent-windows/downloads/index.html.

**Comment by gauchoux** [comment]
Hi @aspcompiler ,

I don't think my environment uses a proxy server and even if it does I have the highest privileges possible.
I used Chrome to download InstallKinesisAgent.ps1.

I've already tried the "Download Manually" section and it doesn't seem to work either.
(I'll still try again just in case !)
Error...

The output:
![image](https://user-images.githubusercontent.com/23196279/52844148-3a583400-3104-11e9-88b2-a475debf0ab9.png)
[Error.txt](https://github.com/awslabs/kinesis-agent-windows/files/2868424/Error.txt)

**Comment by austoonz** [comment]
@gauchoux - Can you confirm which version of the .NET Framework is installed on your system? Based on the error you're seeing, my guess is you're still running an older version of the .NET Framework.

The "[System.IO.Path]::Combine()" method in [.NET Framework 3.5](https://docs.microsoft.com/en-us/dotnet/api/system.io.path?redirectedfrom=MSDN&view=netframework-3.5) only includes a single overload, "Combine(String, String)". In [.NET Framework 4.0 and above](https://docs.microsoft.com/en-us/dotnet/api/system.io.path?redirectedfrom=MSDN&view=netframework-4.0) there are additional overloads on the method (like the one the installer script is using).

For reference, the Amazon Kinesis Agent for Windows requires a minimum of .NET Framework 4.6 to start.

**Comment by gauchoux** [comment]
I have Microsoft .NET Framework 4.7.2 installed on my system, so that can't be the problem... :/

**Comment by aspcompiler** [comment]
Hi @gauchoux, we would like to get more information about your system. Could you run the following Powershell commands and tell us the outputs?

1. $PSVersionTable
This will return the Powershell and CLR versions, etc.

2. \[environment\]::OSVersion.Version
This will return your OS version.

3. gwmi win32_operatingsystem | % caption
This will return your OS string.

Thanks.

**Comment by gauchoux** [comment]
Here are the results of these commands:
[Error.txt](https://github.com/awslabs/kinesis-agent-windows/files/2879112/Error.txt)

For the thread you sent me, I can't seem to find a powershell_ise.exe.config file in my $psHome...

Thanks again for all your help.

**Comment by gauchoux** [comment]
Update,

I tried to install with chocolatey after doing the first step of the thread and I got a different error and the service was installed.
![image](https://user-images.githubusercontent.com/23196279/53001483-0003d500-342b-11e9-96d7-67cba387c70e.png)

**Comment by gauchoux** [comment]
I managed to install it through the "InstallKinesisAgent.ps1" way after updating PowerShell to v5.1 and doing the first step of the thread you posted.
Hope this helps other people.
Thanks again for all your help !
