### ISSUE TITLE
Update NLog to latest version, instead of BETA

### ISSUE THREAD

**Issue by snakefoot** [awslabs/kinesis-agent-windows#5]
https://github.com/awslabs/kinesis-agent-windows/blob/b8980ca6c683504b1e7c717275b07a92a40fbbd8/Amazon.KinesisTap.Hosting/Amazon.KinesisTap.Hosting.csproj#L12

https://github.com/awslabs/kinesis-agent-windows/blob/3b995446156c742e5196fb008b25dcae390dedf5/Amazon.KinesisTap/packages.config#L36

NLog 4.5.0 RTM has been released for NetCore: https://www.nuget.org/packages/NLog/

**Comment by aspcompiler** [comment]
Thanks for your feedback. Fixed in 1.0.0.129. https://github.com/awslabs/kinesis-agent-windows/commit/70be3b68f4866eb33adcaa3f5dbd18a4a81e9ebb
