### ISSUE TITLE
WindowsEventLogSource Suppress Path supported

### ISSUE THREAD

**Issue by thegullion** [awslabs/kinesis-agent-windows#6]
Is the ability to suppress event types supported in the ka4v? example from MS docs below, it's not indicated in the docs how/if the syntax would apply to source query config. 

<QueryList>
  <Query Id="0" Path="Security">
    <Select Path="Security">*</Select>
    <Suppress Path="Security">*[System[(EventID=4624)]] and *[EventData[Data[@Name='TargetUserName'] and (Data ='SYSTEM')]]</Suppress>
  </Query>
</QueryList>

**Comment by aspcompiler** [comment]
Try to set the following Query and see if it works:

      "Query": "<QueryList><Query Id='0' Path='Security'><Select Path='Security'>*</Select><Suppress Path='Security'>*[System[(EventID=4624)]] and *[EventData[Data[@Name='TargetUserName'] and (Data ='SYSTEM')]]</Suppress></Query></QueryList>"
